apiVersion: v1
kind: Service
metadata:
  name: wealth-insights-service
spec:
  type: NodePort
  selector:
    app: wealth-insights
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001  # Access on localhost:30001
