name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests (if you have any)
      run: |
        echo "No tests defined yet"
        # Add your test command here, e.g., pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t portfolio-optimizer .

    # Optional: push image to DockerHub or GitHub Container Registry
    # You can configure secrets for DOCKER_USERNAME and DOCKER_PASSWORD if you want to push images
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image
    #   run: |
    #     docker tag portfolio-optimizer yourdockerhubusername/portfolio-optimizer:latest
    #     docker push yourdockerhubusername/portfolio-optimizer:latest
